### ISSUE TITLE
ClassyFire: consider making `CHEMONTID` the primary ID space

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#1237]
Currently the CURIEs in bioregistry are [classyfire:0004828](https://bioregistry.io/reference/classyfire:/0004828)

But the entries in the OBO file look like this:

```yaml
[Term]
id: CHEMONTID:0004828
name: A-type proanthocyanidins
def: "Proanthocyanidins, which are characterized by the presence of two or more flavonoid units linked to each other by both a 2->7 and a 4->b (or 4->8) interflavonoid CC-bonds." [DOI:10.1039/b101061l, PMID:12430722]
synonym: "proanthocyanidin" BROAD ChEBI_TERM [CHEBI:26267]
xref: DOI:10.1039/b101061l "Karamali Khanbabaee and Teunis van Ree (2001). Tannins: Classification and Definition. Nat. Prod. Rep., 2001, 18, 641–649"
xref: PMID:12430722 "Ferreira D and Slade D (2002). Oligomeric proanthocyanidins: naturally occurring O-heterocycles. Nat Prod Rep., 19(5):517-41."
is_a: CHEMONTID:0000379 ! Proanthocyanidins
created_by: yandj
creation_date: 2015-10-31T18:10:28Z
```

The CURIE should look like the ID as far as possible, so this would point to `CHEMONTID` as primary

(yes including `ID` in the ID space is not ideal but this is what is there...)

However this brings up a governance issue. Does anyone get to come to bioregistry and bypass OBO and claim to be the ontology for X? This argues for sticking with classyfire....

An additional potential confusion here is the classyfire *database* includes both structures and classes

structures have URLs like:
http://classyfire.wishartlab.com/entities/OSWPWNLULQWKAH-UHFFFAOYSA-N

Structures are not in the ontology. This would argue against my proposal for something like classyfire.chemontid vs classyfire.entity but IMO the most important this about classyfire is the classification
