### ISSUE TITLE
merops IDs are not resolving to the correct page

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#439]
There are two entries for this one database in bioregistry; the split was made by identifiers.org:

- merops.family
- merops.inhibitor

This is split doesn't make any sense as I'll explain below
 
The example IDs:

https://bioregistry.io/reference/merops.family:S1
https://bioregistry.io/reference/merops.inhibitor:I31.952

Don't resolve to individual pages. They just take me to the top level https://www.ebi.ac.uk/merops/ -- this is presumably because bioregistry has a sanger URL, and the redirect doesn't preserve the query parameters. 

I think if merops.sanger.ac.uk ==> ebi.ac.uk/merops/ then these particular entries will be fixed, but there are still major issues

*If* identifiers.org is going to split merops, I don't think the current division makes sense

MEROPS is actually divided into [peptidases](https://www.ebi.ac.uk/merops/) and [inhibitors](https://www.ebi.ac.uk/merops/inhibitors/). Within each of these categories there are divisions into

 - the entities themselves - often corresponding to individual genes/proteins
 - families
 - clans

Example peptidase classification:

 * https://www.ebi.ac.uk/merops/cgi-bin/clansum?clan=MA
    * https://www.ebi.ac.uk/merops/cgi-bin/famsum?family=M12
        * https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=M12.334

The leaf nodes typically equate to individual genes or proteins, but there are also groupings e.g. https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=C01.UNA

Example inhibitor classification:

 * https://www.ebi.ac.uk/merops/cgi-bin/clansum?clan=IA
   * https://www.ebi.ac.uk/merops/cgi-bin/famsum?family=I1
       * https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=I01.979

If we want to subdivide the merops namespace in order to support resolution, then we should use clan/family/entry -- the same URLs are used regardless of whether we are talking about peptidases or inhibitors.

E.g.

 * merops.clan => https://www.ebi.ac.uk/merops/cgi-bin/clansum?clan=
 * merops.family => https://www.ebi.ac.uk/merops/cgi-bin/famsum?family=
 * merops.entry => https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=

I don't have a better term than than "entry" - I don't think "protein" is good as the "pepsum" entries are sometimes themselves subfamilies. We could just go with their own nomenclature of "pep"

Note that if we *did* split like this, this would be something of a hard fork from identifiers.org, unless we can coordinate with them to make the same change.

IMO the whole decision by identifiers.org to split databases into sub-namespaces is really problematic but I have commented on this elsewhere.

I believe merops isn't updated any more so I'm not sure how high a priority this all is.

FWIW, this is the entry we have for GO:

```yaml
- database: MEROPS
  name: MEROPS peptidase database
  generic_urls:
    - https://www.ebi.ac.uk/merops/
  entity_types:
    - type_name: protein
      type_id: PR:000000001
      url_syntax: https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=[example_id]
      example_id: MEROPS:A08.001
      example_url: https://www.ebi.ac.uk/merops/cgi-bin/pepsum?id=A08.001
```

Note that unlike identifiers.org we didn't partition the namespace into two, it's all one. But this only works for the leaf nodes in merops. We made a different category error from identifiers.org. But using our scheme we would simply add the new types under the general MEROPS entry.
