### ISSUE TITLE
Generate OLS YAML configuration

### ISSUE THREAD

**Issue by cthoyt** [biopragmatics/bioregistry#579]
Below is what the OLS configuration for a given ontology looks like. It would be valuable to be able to auto-generate one of these for a given Bioregistry record

```yaml
ontology_purl: https://raw.githubusercontent.com/tibonto/aeon/main/aeon.owl
activity_status: active
description:  WIP - NOT READY FOR PRODUCTION - The Academic Event Ontology (AEON) is used to represent information regarding
  academic events.
homepage: https://github.com/tibonto/aeon
id: aeon
layout: ontology_detail
license:
  label: GPL-3.0 License
  url: https://www.gnu.org/licenses/gpl-3.0.en.html
title: Academic Event Ontology
tracker: https://github.com/tibonto/aeon/issues
preferredPrefix: AEON
base_uri: 
  - https://github.com/tibonto/aeon
classification:
  - collection:
definition_property:
  - http://purl.obolibrary.org/obo/IAO_0000115
synonym_property:
  - http://purl.obolibrary.org/obo/IAO_0000118
  - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
  - http://www.geneontology.org/formats/oboInOwl#hasSynonym
repo_url: https://github.com/tibonto/aeon
```

## Questions/comments

- Is the `layout: ontology_detail` just an artifact from OBO Foundry?
- Are there meaningful deviations in `definition_property` or `synonym_property`? or can these just be canned values?
- `collection` is a TIB-specific field.

## See also:

- https://github.com/EBISPOT/OLS/issues/250#issuecomment-486614749 (links to Henriette's [excel sheet](https://github.com/EBISPOT/OLS/files/3116415/SRAO.ontology.configuration.xlsx) describing the schema)
- https://github.com/EBISPOT/OLS/issues/152#issuecomment-598137030 (has the same table better formatted for GitHub)
